version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - "7911:7911"
      - "7922:7922"
      - "7711:7711"
      - "9229:9229"
    environment:
      - REDIS_URI=${REDIS_URI}
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  node_modules:
  postgres_data:
