version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7911:7911"
      - "7922:7922"
    environment:
      - REDIS_URI=${REDIS_URI}
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  redis:
    image: redis
    ports:
      - "6379:6379"
