#ifndef DuelPositions
#define DuelPositions

#define POS_FACEUP_ATTACK    0x1
#define POS_FACEDOWN_ATTACK  0x2
#define POS_FACEUP_DEFENSE   0x4
#define POS_FACEDOWN_DEFENSE 0x8
#define POS_FACEUP           (POS_FACEUP_ATTACK + POS_FACEUP_DEFENSE)
#define POS_FACEDOWN         (POS_FACEDOWN_ATTACK + POS_FACEDOWN_DEFENSE)
#define POS_ATTACK           (POS_FACEUP_ATTACK + POS_FACEDOWN_ATTACK)
#define POS_DEFENSE          (POS_FACEUP_DEFENSE + POS_FACEDOWN_DEFENSE)

#endif