#ifndef DUEL_LOCATIONS
#define DUEL_LOCATIONS

#define LOCATION_DECK 0x01
#define LOCATION_HAND 0x02
#define LOCATION_MZONE 0x04
#define LOCATION_SZONE 0x08
#define LOCATION_GRAVE 0x10
#define LOCATION_REMOVED 0x20
#define LOCATION_EXTRA 0x40
#define LOCATION_OVERLAY 0x80
#define LOCATION_ONFIELD 0x0C
#define LOCATION_FZONE 0x100
#define LOCATION_PZONE 0x200
#define LOCATION_ALL 0x3FF

#endif