#ifndef MESSAGE_TARGETS
#define MESSAGE_TARGETS

enum class MessageTargets
{
	MSG_DIST_TYPE_SPECIFIC_TEAM_DUELIST_STRIPPED,
	MSG_DIST_TYPE_SPECIFIC_TEAM_DUELIST,
	MSG_DIST_TYPE_SPECIFIC_TEAM,
	MSG_DIST_TYPE_EVERYONE_EXCEPT_TEAM_DUELIST,
	MSG_DIST_TYPE_EVERYONE_STRIPPED,
	MSG_DIST_TYPE_EVERYONE,
};

#endif