export class Room {

	constructor(	public readonly roomid: number,
		public readonly roomname: string,
		public readonly roomnotes: string,
		public readonly roommode: number,
		public readonly needpass: boolean,
		public readonly team1: number,
		public readonly team2: number,
		public readonly best_of: number,
		public readonly duel_flag: number,
		public readonly forbidden_types: number,
		public readonly extra_rules: number,
		public readonly start_lp: number,
		public readonly start_hand: number,
		public readonly draw_count: number,
		public readonly time_limit: number,
		public readonly rule: number,
		public readonly no_check: boolean,
		public readonly no_shuffle: boolean,
		public readonly banlist_hash: number,
		public readonly istart: string,
		public readonly main_min: number,
		public readonly main_max: number,
		public readonly extra_min: number,
		public readonly extra_max: number,
		public readonly side_min: number,
		public readonly side_max: number,
		public readonly users: { pos: number; name: string}[]) {}
}