name: PR Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint & format check
        run: pnpm exec biome ci

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

  bash-resources-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Install jq and bats
        run: sudo apt-get update && sudo apt-get install -y jq bats

      - name: Run bash resource tests
        run: bats test/*.bats
